# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
theme_color:
  enable: true
  #main: "#49B1F5"
  main: "#0A0A0A"
  
  paginator: "#00C4B6"
  button_hover: "#FF7242"
  text_selection: "#00C4B6"
  link_color: "#858585"
  hr_color: "#A4D8FA"

# Main menu navigation
# ---------------
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Wiki: https://wiki.qrzbing.cn
  About: /about
  Music: /music
  Friends: /friends
  #XXX: /xxx

# Favicon
# use my-favicon.ico to avoid duplicate favicon of melody theme
# ---------------
# favicon: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/08/avatar_lucio%20_l.png
favicon: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/09/IMG_20190923_132425.png

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /manifest.json
  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  # theme_color: "#1B9EF3"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg


# Highlight theme
# ---------------
highlight_theme: pale night

# code_word_wrap: true or false
code_word_wrap: true

# Nav settings
# ---------------
social:
  #icon_name: url
  github fa: https://github.com/40m41h42t
  paper-plane fa: https://t.me/s/qrzbing
  envelope fa: mailto:qrzbing#foxmail.com
  rss fa: https://blog.qrzbing.cn/atom.xml

# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10


# Local search
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=local-search
# ---------------
local_search:
  enable: false

# MathJax
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=mathjax
# ---------------
mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Toggle fireworks (IE >= 10)
# ---------------
fireworks: false

# Analysis
# ---------------
baidu_analytics: ff97cec996f09596dd444ef4dd5c925d

google_analytics: UA-131763109-1

tencent_analytics: 62826431

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings
# ---------------
# avatar: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/08/avatar_lucio%20_l.png
avatar: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/09/IMG_20190923_132425.png


# top_img: https://raw.githubusercontent.com/40m41h42t/BlogPictures/master/img/933004.jpg
# top_img: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/07/20190706191227_1.jpg
# top_img: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/07/20190622131716_1.jpg
# top_img: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/08/tank_heros_1080P.jpg
top_img: https://raw.githubusercontent.com/40m41h42t/Images/master/2019/09/866283.png

post_meta:
  date_type: created # created or updated 
  categories: true
  tags: true

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/additional-package-support?id=word-counting
wordcount:
  enable: false

toc:
  enable: true
  number: false

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/theme-config?id=auto-excerpt
# auto_excerpt:
#   enable: false
#   length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
  # - itemlist:
  #     img:
  #     text:

# adv:
  # enable: false
  # info: 

# Share System
# ---------------
addThis:
  enable: false
  #pubid: 

# sharejs:
  # enable: false
  # disabled_sites: 

# Comments System
# ---------------
disqus:
  enable: false 
  #shortname: 
  #count: 

# laibili:
  # enable: false
  # uid:

# gitment
  # enable: false
  # owner: 
  # repo: 
  # client_id: 
  # client_secret: 

gitalk:
  enable: true
  client_id: a28396a0fb37fdc22bce
  client_secret: e2e4c983cd284773491d067c6055febad1c23689
  repo: 40m41h42t.github.io
  owner: 40m41h42t
  admin: 40m41h42t
  
####   Using this js for redirect to gitalk container after login
####   See https://github.com/gitalk/gitalk/issues/125
#   js: https://cdn.jsdelivr.net/gh/upupming/gitalk@36368e5dffd049e956cdbbd751ff96c28d8255cf/dist/gitalk.min.js

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is ture
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2018

# footer_custom_text:

ICP:
  enable: false
  #text: 

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: false
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: false
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


# Sidebar Settings
# ---------------
# links_title: Links
# links:
  #Name: url
  # 裂帛碎玉的想法: https://www.vvzero.com/
  # 苏瑞辅的个人网站: https://www.suruifu.com/
  # R·ex / Zeng: https://www.rexskz.info/
  # 善良单纯的板的小窝...: https://yuwenjie.cc/
  # NINJIACODER: http://rayzhao98.top/
  # AddOneG: http://www.addoneg.com/
  # Zedd: https://blog.zeddyu.info/
  # KarlRixon: https://karlrixon.link/
  # l1nk3dHouse: http://showlinkroom.me/
  # Qinmaye's Blog: https://qinmaye.top/
  # Muyun: http://muyun.work/
  # w4rd3n: https://www.hirworld.xyz/
  # Kitty萌新的卧室: https://kit4y.github.io/

# Follow Me Button
# follow:
#   enable: true
#   url: ''
#   text: ''
